'use client';
import { useEffect,useState } from 'react';
import { supabase } from '@/lib/supabase';
export type EntryField={name:string;label?:string;type?:'text'|'number'|'date'|'select';options?:string[];required?:boolean};
export type ModuleDef={title:string;table:string;columns:string[];report?:boolean;entryFields?:EntryField[]};
export function ModulePage({def}:{def:ModuleDef}){
 const [rows,setRows]=useState<Record<string,unknown>[]>([]),[msg,setMsg]=useState(''),[loading,setLoading]=useState(true),[editing,setEditing]=useState(false),[values,setValues]=useState<Record<string,string>>({});
 const load=async()=>{setLoading(true);const {data,error}=await supabase().from(def.table).select('*').limit(100);setRows(data||[]);setMsg(error?.message||'');setLoading(false)};
 useEffect(()=>{load()},[def.table]);
 const set=(key:string,value:string)=>setValues(previous=>({...previous,[key]:value}));
 function csv(){const body=[def.columns.join(','),...rows.map(r=>def.columns.map(c=>JSON.stringify(r[c]??'')).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type:'text/csv'}));a.download=def.table+'.csv';a.click()}
 async function save(event:React.FormEvent){event.preventDefault();const data=Object.fromEntries(Object.entries(values).filter(([,value])=>value!=='').map(([key,value])=>[key,def.entryFields?.find(field=>field.name===key)?.type==='number'?Number(value):value]));const {error}=await supabase().from(def.table).insert(data);if(error){setMsg(error.message);return}setMsg('Saved successfully.');setValues({});setEditing(false);load()}
 return <article><div className="page-title"><div><h1>{def.title}</h1><p>Last refresh: {new Date().toLocaleString()}</p></div><div>{def.entryFields&&<button onClick={()=>setEditing(open=>!open)}>{editing?'Close Entry':'Add New'}</button>}<button onClick={csv}>Export CSV</button><button onClick={()=>print()}>Print Report</button></div></div>
 {editing&&def.entryFields&&<form className="entry-form" onSubmit={save}><h2>New {def.title} record</h2><div className="entry-grid">{def.entryFields.map(field=><label key={field.name}>{field.label||field.name.replaceAll('_',' ')}{field.type==='select'?<select required={field.required} value={values[field.name]||''} onChange={e=>set(field.name,e.target.value)}><option value="">Select…</option>{field.options?.map(option=><option key={option} value={option}>{option}</option>)}</select>:<input required={field.required} type={field.type||'text'} step={field.type==='number'?'any':undefined} value={values[field.name]||''} onChange={e=>set(field.name,e.target.value)}/>}</label>)}</div><button type="submit">Save Record</button><button type="button" className="secondary" onClick={()=>setEditing(false)}>Cancel</button></form>}
 {def.report&&<div className="filters"><select><option>All years</option></select><select><option>All months</option></select><input placeholder="Product"/><input placeholder="POD / Agent / Shipper"/><button>Apply Filter</button></div>}<div className="cards"><div><b>{rows.length}</b><span>Records</span></div><div><b>—</b><span>Calculated from live data</span></div></div>{msg&&<p className={msg==='Saved successfully.'?'success':'error'}>{msg}</p>}<div className="table-wrap"><table><thead><tr>{def.columns.map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={def.columns.length}>Loading…</td></tr>:rows.length?rows.map((r,i)=><tr key={String(r.id||i)}>{def.columns.map(c=><td key={c}>{String(r[c]??'')}</td>)}</tr>):<tr><td colSpan={def.columns.length}>No records found. Use Add New to create the first record.</td></tr>}</tbody></table></div></article>
}

