import { Shell } from '@/components/erp-shell'; import { ModulePage,ModuleDef } from '@/modules/shared/module-page';
const t=(name:string,label?:string,type:'text'|'number'|'date'|'select'='text',required=false,options?:string[])=>({name,label,type,required,options});
const defs:Record<string,ModuleDef>={
'sales/sales-plan':{title:'Sales Plan',table:'sales_plans',columns:['target_month','po_no','service_po_no','shipper_id','unit_rate_usd'],entryFields:[t('target_month','Target month','date',true),t('po_no','PO no','text',true),t('service_po_no'),t('po_date','PO date','date',true),t('shipper_id','Shipper ID','text',true),t('unit_rate_usd','Unit rate USD','number',true)]},
'sales/sales-update':{title:'Sales Update',table:'sales_updates',columns:['sales_date','po_no','shipper_id','shipper_inv_no','invoice_amount_inr'],entryFields:[t('sales_date','Sales date','date',true),t('po_no','PO no','text',true),t('shipper_id','Shipper ID','text',true),t('service_po_no'),t('product_name','Product','text',true),t('billed_containers','Billed containers','number',true),t('shipper_inv_no','Shipper invoice no','text',true),t('invoice_amount_inr','Invoice amount INR','number',true),t('shipper_service_inv_no'),t('service_invoice_amount_inr','Service invoice INR','number')]},
'production/production-update':{title:'Production Update',table:'production_updates',columns:['production_date','shift','machine_no','product_name','production_qty','rejected_qty','complete_small_box_qty','complete_big_box_qty'],entryFields:[t('production_date','Production date','date',true),t('shift',undefined,'select',true,['A','B']),t('machine_no','Machine no','text',true),t('product_name','Product','text',true),t('production_qty','Production qty','number',true),t('rejected_qty','Rejected qty','number'),t('complete_small_box_qty','Complete small boxes','number'),t('complete_big_box_qty','Complete big boxes','number')]},
'purchase/purchase-entry':{title:'Purchase Entry',table:'purchases',columns:['purchase_date','item_type','item_code','supplier_id','qty_purchased','rate','amount','invoice_no'],entryFields:[t('purchase_date','Purchase date','date',true),t('item_type','Item type','select',true,['RM','Packing Item']),t('item_code','Item code','text',true),t('supplier_id','Supplier ID'),t('qty_purchased','Quantity','number',true),t('rate','Rate','number',true),t('invoice_no','Invoice no','text',true)]},
'shipping/shipping-import':{title:'Shipping Master Import & Upsert',table:'import_batches',columns:['source_agent','file_name','upload_date','total_rows','valid_rows','error_rows','status'],entryFields:[t('source_agent','Source agent','text',true),t('file_name','File name','text',true),t('total_rows','Total rows','number'),t('valid_rows','Valid rows','number'),t('error_rows','Error rows','number'),t('status',undefined,'select',false,['Staged','Validated','Imported','Failed'])]},
'utility/master-customer':{title:'Customer Master',table:'customers',columns:['customer_id','customer_name','contact_person','phone','email','gst_tax_id'],entryFields:[t('customer_name','Customer name','text',true),t('address'),t('contact_person'),t('phone'),t('email'),t('gst_tax_id','GST / Tax ID')]},
'utility/master-shipper':{title:'Shipper Master',table:'shippers',columns:['shipper_id','shipper_name','contact','billing_details'],entryFields:[t('shipper_name','Shipper name','text',true),t('address'),t('contact'),t('billing_details')]},
'utility/master-supplier':{title:'Supplier Master',table:'suppliers',columns:['supplier_id','supplier_name','contact','gst_tax_id'],entryFields:[t('supplier_name','Supplier name','text',true),t('contact'),t('address'),t('gst_tax_id','GST / Tax ID')]},
'utility/master-port':{title:'Port Master + Alias Map',table:'ports',columns:['port_id','canonical_name','port_code','country'],entryFields:[t('canonical_name','Port name','text',true),t('port_code','Port code','text',true),t('country',undefined,'text',true)]},
'utility/master-packing-item':{title:'Packing Item Master',table:'packing_items',columns:['item_code','item_name','unit','stock_qty','reorder_level','lead_time_days'],entryFields:[t('item_code','Item code','text',true),t('item_name','Item name','text',true),t('unit',undefined,'text',true),t('stock_qty','Stock qty','number'),t('reorder_level','Reorder level','number'),t('lead_time_days','Lead time days','number')]},
'sales/sales-report':{title:'Sales Report & Discrepancies',table:'v_sales_discrepancies',columns:['shipper_inv_no','sales_date','product_name','invoice_amount_inr'],report:true},'production/fg-stock':{title:'FG Stock',table:'v_fg_stock',columns:['product_name','fg_units','small_boxes','big_boxes','full_containers'],report:true},'production/rm-requirement':{title:'RM Requirement',table:'v_rm_requirements',columns:['product_name','net_production_required','rm_kg_required','stock_qty'],report:true},'shipping/shipping-status':{title:'Shipping Status / MIS',table:'v_shipping_mis',columns:['product','shipper','pod','shipment_count','sea_freight','local_invoice','duty','grand_total'],report:true},'shipping/eta-report':{title:'ETA Report',table:'shipping_master',columns:['shipper_inv_no','eta','product','shipper','pod','container_no'],report:true},'shipping/shipping-schedule':{title:'Shipping Schedule / Forecast',table:'v_container_forecast',columns:['machine_no','sequence_no','product_name','container_number','production_ready_date','stuffing_date'],report:true},'utility/master-bom':{title:'Product / BOM Master',table:'products',columns:['product_name','machine_no','unit_weight_gram','qty_per_container','per_hour_production']},'purchase/stock-transfer':{title:'Stock Transfer Log',table:'stock_transfers',columns:['transfer_date','item_code','qty','adjustment_type','destination_department','notes']},'purchase/stock-audit':{title:'Physical vs System Stock Audit',table:'stock_audits',columns:['audit_date','item_code','system_stock_qty','physical_counted_qty','variance','action']},'admin/user-access':{title:'User & Access Control',table:'user_module_access',columns:['user_id','module_id','access_level']}};
export default async function Page({params}:{params:Promise<{slug:string[]}>}){const {slug}=await params;const key=slug.join('/');return <Shell><ModulePage def={defs[key]||{title:'Dashboard',table:'v_dashboard',columns:['metric','value'],report:true}}/></Shell>}

