create table ports (port_id uuid primary key default gen_random_uuid(), canonical_name text not null unique, port_code text not null unique, country text not null);
create table port_alias_map (raw_text text primary key, port_id uuid not null references ports(port_id), source_agent text not null);
create table customers (customer_id uuid primary key default gen_random_uuid(),customer_name text not null unique,address text,contact_person text,phone text,email text,default_pod uuid references ports(port_id),gst_tax_id text);
create table shippers (shipper_id uuid primary key default gen_random_uuid(),shipper_name text not null unique,address text,contact text,billing_details text);
create table suppliers (supplier_id uuid primary key default gen_random_uuid(),supplier_name text not null unique,contact text,address text,gst_tax_id text);
create table products (product_name text primary key,machine_no text not null,cycle_time_sec_per_shot numeric(12,3) not null check(cycle_time_sec_per_shot>=0),cavity numeric(12,3) not null check(cavity>=0),qty_per_shot numeric(14,3) not null check(qty_per_shot>=0),per_hour_production numeric(14,3) not null check(per_hour_production>=0),per_shift_production_11hr numeric(14,3) not null check(per_shift_production_11hr>=0),per_day_production_2shift numeric(14,3) not null check(per_day_production_2shift>=0),qty_per_container numeric(14,3) not null check(qty_per_container>0),total_box_per_container numeric(14,3) not null check(total_box_per_container>=0),small_box_per_container numeric(14,3) not null check(small_box_per_container>=0),big_box_per_container numeric(14,3) not null check(big_box_per_container>=0),pallet_size text,parts_qty_per_big_box numeric(14,3) not null check(parts_qty_per_big_box>0),parts_qty_per_small_box numeric(14,3) not null check(parts_qty_per_small_box>0),box_qty_per_pallet numeric(14,3) not null check(box_qty_per_pallet>=0),total_pallets_per_container numeric(14,3) not null check(total_pallets_per_container>=0),nett_weight_kg numeric(14,3) not null check(nett_weight_kg>=0),unit_weight_gram numeric(14,6) not null check(unit_weight_gram>=0),total_weight numeric(14,3) not null check(total_weight>=0),stripe_bundle_per_container numeric(14,3) not null default 0,label_sticker_roll_per_container numeric(14,3) not null default 0,wad_roll_per_container numeric(14,3) not null default 0,o_ring_per_container numeric(14,3) not null default 0);
create table raw_materials (rm_code text primary key,rm_name text not null,unit text not null default 'KG',stock_qty numeric(16,3) not null default 0 check(stock_qty>=0),reorder_level numeric(16,3) not null default 0,lead_time_days integer not null default 0 check(lead_time_days>=0));
create table product_materials (product_name text references products(product_name) on delete cascade,rm_code text references raw_materials(rm_code),unit_weight_gram numeric(14,6) not null check(unit_weight_gram>=0),primary key(product_name,rm_code));
create table packing_items (item_code text primary key,item_name text not null unique,unit text not null,stock_qty numeric(16,3) not null default 0 check(stock_qty>=0),reorder_level numeric(16,3) not null default 0,lead_time_days integer not null default 0 check(lead_time_days>=0));

