create or replace function has_any_erp_access() returns boolean language sql stable security invoker set search_path=public as $$select exists(select 1 from user_module_access where user_id=auth.uid() and access_level in('View','Edit'))$$;
create or replace function has_any_erp_edit_access() returns boolean language sql stable security invoker set search_path=public as $$select exists(select 1 from user_module_access where user_id=auth.uid() and access_level='Edit')$$;
create or replace function validate_purchase_item() returns trigger language plpgsql security invoker set search_path=public as $$begin if new.item_type='RM' and not exists(select 1 from raw_materials where rm_code=new.item_code) then raise exception 'Invalid raw material item code';end if;if new.item_type='Packing Item' and not exists(select 1 from packing_items where item_code=new.item_code) then raise exception 'Invalid packing item code';end if;return new;end $$;
create trigger purchase_item_validation before insert or update on purchases for each row execute function validate_purchase_item();
do $$declare r record;begin for r in select tablename from pg_tables where schemaname='public' and tablename not in('users','module_master','user_module_access','role_templates','role_template_access','audit_log') loop execute format('alter table %I enable row level security',r.tablename); execute format('create policy %I on %I for select to authenticated using (has_any_erp_access())',r.tablename||'_read',r.tablename); execute format('create policy %I on %I for insert to authenticated with check (has_any_erp_edit_access())',r.tablename||'_insert',r.tablename); execute format('create policy %I on %I for update to authenticated using (has_any_erp_edit_access()) with check (has_any_erp_edit_access())',r.tablename||'_update',r.tablename); execute format('create policy %I on %I for delete to authenticated using (has_any_erp_edit_access())',r.tablename||'_delete',r.tablename);end loop;end $$;
alter table audit_log enable row level security; create policy audit_read on audit_log for select to authenticated using(has_any_erp_access());
create or replace function handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.users(user_id,name,email) values(new.id,coalesce(new.raw_user_meta_data->>'name',''),new.email) on conflict(user_id) do update set email=excluded.email;return new;end $$;
revoke execute on function handle_new_user() from public; create trigger on_auth_user_created after insert on auth.users for each row execute function handle_new_user();

